### ISSUE TITLE
Internal member methods from objects in 2nd stage are not resolved by VSCode or Pycharm

### ISSUE THREAD

**Issue by EdgarMerger** [EdgarMerger/SiemensEDA_Python_Interface#1]
After importing ifc module files, some objects can point out the internal member methods, while others cannot. I wonder if you have encountered this problem?
![image](https://github.com/user-attachments/assets/a5f579fc-6a15-483f-bee1-4078dbcf172e)

This is expected, because you are actually in the 2nd level of Methods.

See with objApplication.GetProjectData() you get internal member methods because objApplication has been annotated already using statement objApplication : IVdApp = None. That is why VScode (and Pycharm similarly) knows where to look for internal member methods. In the second stage it does not know because there is no annotation for it.

What one can do is to add the annotation and then do this
![image](https://github.com/user-attachments/assets/007e29b8-7b7c-4d56-84cb-3a494146a1ab)

The designer_ifc.py might be upgradeable in a way so that even the second stage of internal members can be resolved by VScode without additional annotation of the class type. I will use add that as an issue in Github and might look at that in the future.

**Comment by billgong168** [comment]
OK. It is so nice. Additional Please think about the second stage, the third stage, the fourth, and so on, of internal members. In this way users can handle it very conveniently.  Thanks. You are my superstar! 👍

**Comment by EdgarMerger** [comment]
One way to do this enable a deeper autocompletion is by generating stub files (*.pyi). This can be accomplished e.g. by `"mypy stubgen"`

**Comment by EdgarMerger** [comment]
@billgong168 : Please test new "designer_automation". I have created deeper object hinting.

**Comment by billgong168** [comment]
OK.   I found that Pycharm could not recognize the IStringList type. Does VScode can recognize the type?  I can not upload pictures, so please see the community.

**Comment by billgong168** [comment]
ok

**Comment by EdgarMerger** [comment]
Added a forward declaration statement in *_ifc.py files vias sniff_*.py files.
Wth 0.3 release that should work.

**Comment by billgong168** [comment]
ok   I will test.
